name: Build iOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 检出代码
      - name: Check out repository
        uses: actions/checkout@v2

      # 设置 Node.js 环境（如果需要）
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 安装 CocoaPods（如果项目使用了 CocoaPods）
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod install --project-directory=ios

      # 构建 iOS 应用
      - name: Build iOS app
        run: |
          cd ios
          xcodebuild -workspace splayer.xcworkspace -scheme splayer -configuration Release archive -archivePath $GITHUB_WORKSPACE/build/splayer.xcarchive

      # 导出 .ipa 文件
      - name: Export .ipa file
        run: |
          xcodebuild -exportArchive -archivePath $GITHUB_WORKSPACE/build/YourApp.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $GITHUB_WORKSPACE/build

      # 上传构建产物
      - name: Upload .ipa to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/splayer.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
